theme = "default"
client_id = "b9f1cccfbd9946cfac9fe93220eaed80"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "||"
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Rectangle"
enable_media_control = true
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "arch"
seek_duration_secs = 5
cover_image_scale = 0.5

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "poopipy"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = true
